[package]
name = "logbook"
version = "0.1.0"
authors = ["Carlo Panzi <carlo.panzi@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.2.1"
chrono = { version = "0.4", features = ["serde"] }
mustache = "0.9.0"