[package]
name = "logbook"
version = "0.3.0"
authors = ["Carlo Panzi <carlo.panzi@gmail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "2.31", features = ["yaml"] }
mustache = "0.9.0"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.2.1"